logger:
  level: info
  encoding: console
  outputPaths:
    - stdout
  errorOutputPaths:
    - stderr
  enableStackTrace: false

application:
  shutdownTimeout: 10s

server:
  port: 8070

gateway:
  address: localhost
  port: 8080