logger:
  level: info
  encoding: console
  outputPaths:
    - stdout
  errorOutputPaths:
    - stderr
  enableStackTrace: false

application:
  shutdownTimeout: 10s

server:
  port: 8080

library:
  address: localhost
  port: 8060

reservation:
  address: localhost
  port: 8070

rating:
  address: localhost
  port: 8050
